modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "${mod_license}"
issueTrackerURL = "https://github.com/alRex-U/Throwability/issues/" #optional
[[mods]] #mandatory
modId = "throwability" #mandatory
version = "${mod_version}" #mandatory
displayName = "Throwability" #mandatory
updateJSONURL = "https://www.curseforge.com/minecraft/mc-mods/throwability" #optional
displayURL = "https://www.curseforge.com/minecraft/mc-mods/throwability" #optional
authors = "alRex-U" #optional
description = '''
    This mod enable players to throw every items.
    Let's throw a TNT to your friends!
'''
[[dependencies.throwability]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "${forge_version_range}" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.throwability]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
